# Generated by Django 4.0.3 on 2022-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_course_weeks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor_name',
            new_name='instructor',
        ),
        migrations.AlterField(
            model_name='course',
            name='weeks',
            field=models.IntegerField(default=0),
        ),
    ]
